### ISSUE TITLE
[Feature]:Enable Dark Mode

### ISSUE THREAD

**Issue by JiyaGupta-cs** [1010varun/weather-app#14]
Almost every website today has a dark mode feature as it reduces eye strain and improves readability in low-light conditions.

Introducing Dark and Light Mode Feature in the website would enhance it's features.

**Comment by JiyaGupta-cs** [comment]
@1010varun Please assign this issue to me under IWOC

**Comment by geek-nikhil** [comment]
@1010varun  I have hands on experienced on this.
Please assign me this issue.

**Comment by Bhupendra3444** [comment]
hey @1010varun please assign me this under iwoc.

**Comment by JiyaGupta-cs** [comment]
Hey @Bhupendra3444 
I am already working on this issue
But you can take some other issue.

**Comment by 1010varun** [comment]
@JiyaGupta-cs, please solve the assigned issue before asking to assign the new issue.

**Comment by Sakshamjain98** [comment]
@1010varun sir please assign this issue to me

**Comment by 1010varun** [comment]
@geek-nikhil solve the build issues in PR

**Comment by 1010varun** [comment]
@JiyaGupta-cs assigning it to you due to inactivity
