### ISSUE TITLE
Page is  not responsive.

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [1010varun/weather-app#21]
Description
Is your feature request related to a problem? Please describe.
The site is not responsive; it is breaking. If you look at the navbar, you will notice.

![image](https://github.com/1010varun/weather-app/assets/69814563/eaf7db3f-df92-462e-a652-db45f7a0fa7f)

Describe the solution you'd like
I aim to add responsive CSS.

Checklist

- [x] I have checked the existing issues
- [x] I have read the Contributing Guidelines
 - [x] I am willing to work on this issue (optional)
- [x]  I am an IWOC'24 contributor

**Comment by 1010varun** [comment]
@BamaCharanChhandogi go on with it

**Comment by BamaCharanChhandogi** [comment]
#31

**Comment by 1010varun** [comment]
Fixed with PR #31
