### ISSUE TITLE
Uncovered weather descriptions leads to broken backgrounds

### ISSUE THREAD

**Issue by TheDarkW3b** [1010varun/weather-app#24]
Weather description such as fog is not covered in the `determineweatherurl()` function leading to broken backgrounds.

Eg: If weather description is `fog` 
![2024-01-13_23-58](https://github.com/1010varun/weather-app/assets/54339318/126d1daf-6f79-4628-990c-b2d761130959)

Broken background as fog description is not covered in the`determineweatherurl()`
![image](https://github.com/1010varun/weather-app/assets/54339318/61155ba7-8796-451b-a963-695e1907aec5)

**Comment by hemant933** [comment]
assign it to me plz

**Comment by TheDarkW3b** [comment]
Also please assign the issue under `iwoc2024`
Thanks ;)
