### ISSUE TITLE
Adding "enter" button functionality

### ISSUE THREAD

**Issue by TheDarkW3b** [1010varun/weather-app#27]
**Issue Summary**:
Currently, the page lacks the functionality to trigger certain actions when the Enter key is pressed. This feature is commonly expected by users, especially in input fields or form submissions. 
Upon pressing enter, the cursor should shift to the other input tag and once filled, the next enter would submit the form.

**Solution**:
Implement event listeners or handlers for the Enter key within relevant page elements, allowing the associated actions to be triggered. 

**PS: Assign me this issue under `iwoc2024`**

**Comment by 1010varun** [comment]
@TheDarkW3b assigning it to you go ahead
