### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by AbhineshJha** [1010varun/weather-app#30]
Adding code of conduct file in the repository 
Can u assign me with this issue  under IWOC

**Comment by 1010varun** [comment]
@AbhineshJha can you describe this issue briefly and its need...

**Comment by AbhineshJha** [comment]
sir @1010varun  A CODE_OF_CONDUCT.md file in a GitHub repository outlines expected behavior, unacceptable conduct, reporting guidelines, consequences for violations, and contact information for maintaining a positive and inclusive community. It sets standards for respectful collaboration and provides a mechanism for addressing violations.

**Comment by 1010varun** [comment]
@1010varun seems interesting assigning it to you
