### ISSUE TITLE
Typographical Errors in README.md

### ISSUE THREAD

**Issue by TheDarkW3b** [1010varun/weather-app#34]
**Description**
I have come across a few typographical errors in the README.md file of the project. These errors may cause confusion or hinder understanding for new users or developers. I would like to bring them to your attention so that they can be corrected for better clarity and consistency.

**Comment by TheDarkW3b** [comment]
If you are accepting this:
Please follow the following order:
* Assign the issue first under `iwoc2024`
* Label it
* Merge the PR

Thank you ;)

**Comment by 1010varun** [comment]
Assigning it to you
