### ISSUE TITLE
[Feature] Location Suggestion for Weather App

### ISSUE THREAD

**Issue by TheDarkW3b** [1010varun/weather-app#39]
## Description:
The current weather app lacks a convenient way for users to input their location. Manually typing the location can be error-prone and time-consuming. This issue is raised to propose the addition of a location suggestion feature to enhance user experience.

Something like
![Screenshot (1)](https://github.com/1010varun/weather-app/assets/54339318/a95805f2-ee2c-403c-a4dc-fc72c1cbf693)
*** 
I will find the suitable API for that and will also integrate the feature with both input fields (selecting city from dropdown would replace both the city and country input fields accordingly)
***
**Please assign me this issue under `iwoc2024`**

**Comment by 1010varun** [comment]
seems interesting go ahead assigning it to you

**Comment by TheDarkW3b** [comment]
since i have to find the API and also integrate it well with the webapp. I think it should be `hard`
Making a footer also got the `medium` label, dual work shouldn’t be `hard`?
Let me know your views on it..
Thank you ;)

**Comment by 1010varun** [comment]
Making it hard raise a PR.
