### ISSUE TITLE
enhance: add Github profile  link on footer 

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [1010varun/weather-app#59]
I want to add the GitHub profile link of @1010varun on the footer. 
when the user clicks `©1010varun`, it redirects to the GitHub profile page.

<img width="237" alt="image" src="https://github.com/1010varun/weather-app/assets/69814563/e7341f16-5166-4b0c-8431-6d276932f1cc">

**Comment by 1010varun** [comment]
also correct the footer that you have fixed earlier it is not at its correct location when we fetch some info

![image](https://github.com/1010varun/weather-app/assets/104075461/eacc33e1-3755-4c53-87cf-c4b17c4d5344)

making this issue hard solve both the issues
